#!/bin/sh

/usr/bin/dbus-send --system   --dest=org.ganesha.nfsd --type=method_call /org/ganesha/nfsd/admin org.ganesha.nfsd.admin.shutdown

if test "$1" -eq 256 ; then
  e=$((128 + $2))
else
  e="$1"
fi

cat /var/log/ganesha/ganesha.conf | tail -200

echo "$e" > /run/s6-linux-init-container-results/exitcode
